baseURL = "https://loic.vandenberghe.ch"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/experience.css"
  [[params.plugins.css]]
  URL = "css/contact.css"
  [[params.plugins.css]]
  URL = "css/education.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

#  [[menu.header]]
#  name = "About"
#  URL = "#about"
#  weight = 2
 
  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 2
  
  
  [[menu.header]]
  name = "Projects"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "GitHub"
  URL = "https://github.com/loiclovitana"
  weight = 3

  [[menu.footer]]
  name = "Linkedin"
  URL = "https://www.linkedin.com/in/lo%C3%AFc-vandenberghe-693729166/"
  weight = 4


[params]

  sections = ["showcase","skills_tag", "education", "experience", "client_and_work", "contact"]

  homepageExperienceCount = 999

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "Loïc"
    text2 = "Vandenberghe"

  [params.footer]
      copyright = "© Loïc Vandenberghe."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"



[security]
  [security.funcs]
    getenv = ['^HUGO_']



[taxonomies]
  skill = 'skills'
  category = 'categories'