name: Build hugo website

on:
  workflow_call:
  pull_request:
    types: [opened, reopened]
    branches:
        - 'master'


  # Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.133.0
      HUGO_CONTACT_EMAIL: ${{vars.HUGO_CONTACT_EMAIL}}
      HUGO_CONTACT_PHONE: ${{vars.HUGO_CONTACT_PHONE}}
      HUGO_BASE_URL: ${{ vars.HUGO_BASE_URL}}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb     
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          HUGO_CONTACT_API_KEY: ${{secrets.HUGO_CONTACT_API_KEY}}
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL ${HUGO_BASE_URL}        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
